require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - exe/**/*
    - tmp/**/*
    - vendor/**/*
    - gemfiles/**/*
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics:
  Enabled: false

Security/MarshalLoad:
  Enabled: false
  
Style/PercentLiteralDelimiters:
  Exclude:
    - "*.gemspec"

Style/RedundantPercentQ:
  Exclude:
    - "*.gemspec"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
